parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Shared\Application\Bus\SyncQueryHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: sync.query.bus}
        App\Shared\Application\Bus\AsyncCommandHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: messenger.bus.default}

    App\Geo\Domain\:
        resource: '../../src/Geo/Domain/'

    App\Geo\Infrastructure\:
        resource: '../../src/Geo/Infrastructure/'

    App\Geo\Application\:
        resource: '../../src/Geo/Application/'
        exclude:
            - '../../src/Geo/Application/**/*Query.php'
            - '../../src/Geo/Application/**/*Command.php'

    bookit.doctrine.middleware.search_path.geo:
        class: App\Shared\Infrastructure\Doctrine\SearchPathMiddleware
        arguments:
            $schema: 'geo'
        tags:
            - {name: doctrine.middleware, connection: geo}
