parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Shared\Application\Bus\SyncCommandHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: sync.command.bus}

    App\Onboarding\Application\:
        resource: '../../src/Onboarding/Application/'
        exclude:
            - '../../src/Onboarding/Application/**/*Command.php'

    App\Onboarding\UI\:
        resource: '../../src/Onboarding/UI/'
        exclude:
            - '../../src/Onboarding/UI/**/*Request.php'

    App\Onboarding\Infrastructure\:
        resource: '../../src/Onboarding/Infrastructure/'

    App\Onboarding\Application\Port\OrganizationRegistrarInterface:
        class: App\Onboarding\Infrastructure\Adapter\OrganizationRegistrarAdapter

    App\Onboarding\Application\Port\OwnerOperatorRegistrarInterface:
        class: App\Onboarding\Infrastructure\Adapter\OwnerOperatorRegistrarAdapter

when@test:
    services:
        App\Security\Application\Contract\AccountRegistrarInterface:
            class: App\Tests\Security\Infrastructure\NullAccountRegistrar
