parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Shared\Application\Bus\SyncCommandHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: sync.command.bus}
        App\Shared\Application\Bus\SyncQueryHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: sync.query.bus}

    App\Pricing\Domain\:
        resource: '../../src/Pricing/Domain/'
        exclude:
            - '../../src/Pricing/Domain/Model/'

    App\Pricing\Application\:
        resource: '../../src/Pricing/Application/'
        exclude:
            - '../../src/Pricing/Application/**/*Command.php'
            - '../../src/Pricing/Application/**/*Query.php'

    App\Pricing\UI\:
        resource: '../../src/Pricing/UI/'
        exclude:
            - '../../src/Pricing/UI/**/*Request.php'
