# config/services/reservation.yaml
parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Shared\Application\Bus\SyncCommandHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: sync.command.bus}
        App\Shared\Application\Bus\SyncQueryHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: sync.query.bus}
        App\Shared\Application\Bus\AsyncCommandHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: messenger.bus.default}

    App\Reservation\Domain\:
        resource: '../../src/Reservation/Domain/'
        exclude:
            - '../../src/Reservation/Domain/Model/'

    App\Reservation\Application\:
        resource: '../../src/Reservation/Application/'
        exclude:
            - '../../src/Reservation/Application/**/*Command.php'
            - '../../src/Reservation/Application/**/*Query.php'

    App\Reservation\Infrastructure\:
        resource: '../../src/Reservation/Infrastructure/'

    App\Reservation\UI\:
        resource: '../../src/Reservation/UI/'
        exclude:
            - '../../src/Reservation/UI/**/*Request.php'

    App\Reservation\Infrastructure\Persistence\Doctrine\ReservationRepository:
        arguments:
            $reservationConnection: '@doctrine.dbal.reservation_connection'

    bookit.doctrine.middleware.search_path.reservation:
        class: App\Shared\Infrastructure\Doctrine\SearchPathMiddleware
        arguments:
            $schema: 'reservation'
        tags:
            - {name: doctrine.middleware, connection: reservation}
