parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Shared\Application\Bus\SyncCommandHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: sync.command.bus}
        App\Shared\Application\Bus\SyncQueryHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: sync.query.bus}

    App\Room\Domain\:
        resource: '../../src/Room/Domain/'
        exclude:
            - '../../src/Room/Domain/Model/'

    App\Room\Application\:
        resource: '../../src/Room/Application/'
        exclude:
            - '../../src/Room/Application/**/*Exception.php'
            - '../../src/Room/Application/**/*Command.php'
            - '../../src/Room/Application/**/*Query.php'

    App\Room\Infrastructure\:
        resource: '../../src/Room/Infrastructure/'
        exclude:
            - '../../src/Room/Infrastructure/**/*Exception.php'

    App\Room\UI\:
        resource: '../../src/Room/UI/'
        exclude:
            - '../../src/Room/UI/**/*Request.php'

    App\Room\Domain\Port\RoomTypeIdGeneratorInterface:
        class: App\Room\Infrastructure\Service\RoomTypeIdGenerator

    App\Room\Domain\Port\RoomTypeHasRoomsInterface:
        class: App\Room\Infrastructure\Persistence\Doctrine\RoomTypeHasRoomsChecker

    App\Room\Domain\Port\RoomTypeExistsInterface:
        class: App\Room\Infrastructure\Persistence\Doctrine\RoomTypeExistenceChecker

    App\Room\Domain\Port\RoomCapacityFinderInterface:
        class: App\Room\Infrastructure\Persistence\Doctrine\RoomCapacityFinder

    bookit.doctrine.middleware.search_path.room:
        class: App\Shared\Infrastructure\Doctrine\SearchPathMiddleware
        arguments:
            $schema: 'room'
        tags:
            - {name: doctrine.middleware, connection: room}
