parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        App\Shared\Application\Bus\SyncQueryHandlerInterface:
            tags:
                - {name: messenger.message_handler, bus: sync.query.bus}

    App\Search\Infrastructure\:
        resource: '../../src/Search/Infrastructure/'

    App\Search\UI\:
        resource: '../../src/Search/UI/'
        exclude:
            - '../../src/Search/UI/**/*Request.php'

    App\Search\Application\:
        resource: '../../src/Search/Application/'
        exclude:
            - '../../src/Search/Application/**/*Query.php'

    App\Search\Infrastructure\EventListener\StarRatingClassifiedListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\EventListener\HotelAmenityDeclaredListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\EventListener\RoomTypeRegisteredListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'
            $hotelConnection: '@doctrine.dbal.hotel_connection'

    App\Search\Infrastructure\EventListener\RoomTypeUpdatedListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\EventListener\RoomTypeAmenityDeclaredListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\EventListener\RoomTypeDeletedListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\EventListener\RoomRegisteredListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\EventListener\BlockedPeriodCreatedListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\EventListener\BlockedPeriodDeletedListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\EventListener\AvailabilityHoldCreatedListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\EventListener\AvailabilityHoldDeletedListener:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Infrastructure\Finder\DbalAvailableRoomTypeFinder:
        arguments:
            $connection: '@doctrine.dbal.search_connection'

    App\Search\Domain\Port\AvailableRoomTypeFinderInterface: '@App\Search\Infrastructure\Finder\DbalAvailableRoomTypeFinder'

    bookit.doctrine.middleware.search_path.search:
        class: App\Shared\Infrastructure\Doctrine\SearchPathMiddleware
        arguments:
            $schema: 'search'
        tags:
            - {name: doctrine.middleware, connection: search}
