parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\Application\Contract\AccountRegistrarInterface: '@App\Security\Infrastructure\Keycloak\KeycloakAccountRegistrar'
    App\Security\Infrastructure\Keycloak\KeycloakHttpClientInterface: '@App\Security\Infrastructure\Keycloak\KeycloakHttpClient'

    App\Security\Infrastructure\:
        resource: '../../src/Security/Infrastructure/'
        exclude:
            - '../../src/Security/Infrastructure/**/*Exception.php'


    App\Security\Infrastructure\Keycloak\KeycloakHttpClient:
        arguments:
            $keycloakBaseUrl: '%env(KEYCLOAK_BASE_URL)%'
            $keycloakRealm: '%env(KEYCLOAK_REALM)%'
            $keycloakClientId: '%env(KEYCLOACK_CLIENT_ID)%'
            $keycloakClientSecret: '%env(KEYCLOACK_CLIENT_SECRET)%'

    App\Security\Infrastructure\Persistence\IdentityMappingRepository:
        arguments:
            $connection: '@doctrine.dbal.security_connection'

    bookit.doctrine.middleware.search_path.security:
        class: App\Shared\Infrastructure\Doctrine\SearchPathMiddleware
        arguments:
            $schema: 'security'
        tags:
            - {name: doctrine.middleware, connection: security}
