parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\Application\Contract\AccountRegistrarInterface: '@App\Security\Infrastructure\Keycloak\KeycloakAccountRegistrar'

    App\Security\Infrastructure\:
        resource: '../../src/Security/Infrastructure/'
        exclude:
            - '../../src/Security/Infrastructure/**/*Exception.php'

    App\Security\Infrastructure\Keycloak\KeycloakRetryPolicy:
        arguments:
            $maxAttempts: '%env(int:KEYCLOAK_MAX_RETRIES)%'
            $baseDelayMs: '%env(int:KEYCLOAK_RETRY_BASE_DELAY)%'

    App\Security\Infrastructure\Keycloak\KeycloakHttpClient:
        arguments:
            $keycloakBaseUrl: '%env(KEYCLOAK_BASE_URL)%'
            $keycloakRealm: '%env(KEYCLOAK_REALM)%'
            $keycloakClientId: '%env(KEYCLOACK_CLIENT_ID)%'
            $keycloakClientSecret: '%env(KEYCLOACK_CLIENT_SECRET)%'

    App\Security\Infrastructure\Keycloak\KeycloakHttpClientInterface: '@App\Security\Infrastructure\Keycloak\KeycloakHttpClient'

    bookit.doctrine.middleware.search_path.security:
        class: App\Shared\Infrastructure\Doctrine\SearchPathMiddleware
        arguments:
            $schema: 'security'
        tags:
            - {name: doctrine.middleware, connection: security}

    App\Security\Infrastructure\Keycloak\KeycloakJwksProvider:
        arguments:
            $httpClient: '@http_client'
            $cache: '@cache.app'
            $keycloakBaseUrl: '%env(KEYCLOAK_BASE_URL)%'
            $keycloakRealm: '%env(KEYCLOAK_REALM)%'

    App\Security\Infrastructure\Keycloak\KeycloakJwksProviderInterface: '@App\Security\Infrastructure\Keycloak\KeycloakJwksProvider'

    App\Security\Infrastructure\Keycloak\BearerTokenAuthenticator:
        arguments:
            $jwksProvider: '@App\Security\Infrastructure\Keycloak\KeycloakJwksProviderInterface'
            $keycloakIssuer: '%env(KEYCLOAK_BASE_URL)%/realms/%env(KEYCLOAK_REALM)%'
