parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Shared\:
        resource: '../../src/Shared/'
        exclude:
            - '../../src/Shared/**/*Exception.php'

    App\Shared\Infrastructure\Transaction\DoctrineTransactionManager:
        arguments:
            $bookit: '@doctrine.dbal.bookit_connection'

