parameters:
    app.api.current_version: 'v1'
    app.api.deprecated_versions: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Shared\:
        resource: '../../src/Shared/'
        exclude:
            - '../../src/Shared/**/*Exception.php'
            - '../../src/Shared/Infrastructure/Doctrine/SearchPathMiddleware.php'

    App\Shared\Infrastructure\Http\ApiVersionRedirectListener:
        arguments:
            $currentApiVersion: '%app.api.current_version%'
            $deprecatedVersions: '%app.api.deprecated_versions%'

    App\Shared\Infrastructure\Http\ApiDeprecationResponseListener:
        arguments:
            $currentApiVersion: '%app.api.current_version%'
            $deprecatedVersions: '%app.api.deprecated_versions%'

    App\Shared\UI\Console\GenerateEventsCatalogCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Shared\UI\Console\GenerateContextMapCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

