parameters: {}

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Shared\:
        resource: '../../src/Shared/'
        exclude:
            - '../../src/Shared/**/*Exception.php'

