framework:
    messenger:
        default_bus: messenger.bus.default
        buses:
            sync.command.bus:
                middleware:
                    - 'App\Shared\Infrastructure\Bus\Middleware\ExceptionThrowerMiddleware'
            sync.query.bus:
                middleware:
                    - 'App\Shared\Infrastructure\Bus\Middleware\ExceptionThrowerMiddleware'
            messenger.bus.default:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            commands:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
                    jitter: 0.1
                failure_transport: failed_commands
                options:
                    auto_setup: false
                    exchange:
                        name: 'bookit.commands.exchange'
                    queues:
                        bookit.commands: ~

            failed_commands:
                dsn: 'doctrine://bookit?table_name=bookit_failed_commands'
                options:
                    auto_setup: false

        routing:
            App\Shared\Application\Bus\AsyncCommandInterface: command

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
