<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260515190100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create bookit_failed_commands table for Symfony Messenger failed transport';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS bookit_failed_commands (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body        TEXT NOT NULL,
                headers     TEXT NOT NULL,
                queue_name  VARCHAR(190) NOT NULL,
                created_at  TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_bookit_failed_commands_queue_name ON bookit_failed_commands (queue_name)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_bookit_failed_commands_available_at ON bookit_failed_commands (available_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_bookit_failed_commands_delivered_at ON bookit_failed_commands (delivered_at)');

        $this->addSql("COMMENT ON TABLE bookit_failed_commands IS 'Contains failed async commands routed to the failed_commands transport. A new row is added each time a command from the commands transport fails. Used for retry and failure monitoring.'");
        $this->addSql('COMMENT ON COLUMN bookit_failed_commands.id IS \'Identifiant unique auto-incrémenté\'');
        $this->addSql('COMMENT ON COLUMN bookit_failed_commands.body IS \'Corps sérialisé du message Messenger\'');
        $this->addSql('COMMENT ON COLUMN bookit_failed_commands.headers IS \'En-têtes sérialisés du message Messenger (métadonnées, stamps)\'');
        $this->addSql("COMMENT ON COLUMN bookit_failed_commands.queue_name IS 'Nom de la queue d''origine du message'");
        $this->addSql('COMMENT ON COLUMN bookit_failed_commands.created_at IS \'Date de création du message dans le transport (DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bookit_failed_commands.available_at IS \'Date à partir de laquelle le message peut être rejoué (DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bookit_failed_commands.delivered_at IS \'Date de livraison du message, NULL si non encore consommé (DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS bookit_failed_commands');
    }
}
