imports:
    - { resource: './services/shared.yaml' }
    - { resource: './services/hotel.yaml' }
    - { resource: './services/room.yaml' }
    - { resource: './services/booker.yaml' }
    - { resource: './services/availability.yaml' }
    - { resource: './services/pricing.yaml' }
    - { resource: './services/reservation.yaml' }
    - { resource: './services/exceptions.yaml' }
    - { resource: './services/payment.yaml' }
    - { resource: './services/notification.yaml' }
    - { resource: './services/search.yaml' }

